# Generated by Django 4.2.7 on 2023-11-27 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_username_user_avatar_user_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'admin'), ('editor', 'editor'), ('member', 'member')], default='member', verbose_name='роль пользователя'),
        ),
    ]
