# Generated by Django 4.2.7 on 2023-11-25 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0005_remove_payment_paid_course_or_lesson_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='course',
            new_name='paid_course',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='lesson',
            new_name='paid_lesson',
        ),
    ]
