# Generated by Django 4.2.7 on 2023-11-26 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0006_rename_course_payment_paid_course_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='paid_course',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='paid_lesson',
            new_name='lesson',
        ),
    ]
